[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_SUPABASE_URL = "https://your-project-ref.supabase.co"
  VITE_SUPABASE_ANON_KEY = "your-anon-key-here"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_TEMPO = "false"
  VITE_SUPABASE_URL = "https://your-project-ref.supabase.co"
  VITE_SUPABASE_ANON_KEY = "your-anon-key-here"

[context.deploy-preview.environment]
  VITE_TEMPO = "false"
  VITE_SUPABASE_URL = "https://your-project-ref.supabase.co"
  VITE_SUPABASE_ANON_KEY = "your-anon-key-here"

[context.branch-deploy.environment]
  VITE_TEMPO = "false"
  VITE_SUPABASE_URL = "https://your-project-ref.supabase.co"
  VITE_SUPABASE_ANON_KEY = "your-anon-key-here"